messages:
  noPermission: "You don't have enough permissions to do that..."
  notAPlayer: "You don't have any legs or hands, I think you're not a player..."
  spySuccess: "You're now in Spectator Mode !"
  unspySuccess: "You're now in the default gamemode."
  backSuccess: "You've been teleported to your last /spy !"
  backFail: "There are no more positions saved."
  antiSuffocation: "Warning ! You can suffocate if you reappear here... Type /spy force to do it anyway."
settings:
  nightVision: true