main: eu.bidulaxstudio.spectathor.SpectaThor
name: SpectaThor
version: 1.0
api-version: 1.19
author: BidulaxStudio
commands:
  spy:
    description: Change your gamemode to spectator mode
    permission: spectathor.spy
    usage: /spy
  back:
    description: Teleport you to your last /spy
    permission: spectathor.spy
    usage: /back
permissions:
  spectathor.spy:
    description: Allows you to use the /spy and /back commands
    default: op
  spectathor.autospy:
    description: Sets you automatically in spectator mode when you log in
    default: op